name: .NET 5 CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: .NET 5 Application
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - run: dotnet build src/BTech.ExpenseSystem.WebAPI/BTech.ExpenseSystem.WebAPI.csproj
      - run: dotnet test tests/BTech.ExpenseSytem.UnitTests/BTech.ExpenseSytem.UnitTests.csproj